version: '3.4'

services:
  web:
    build:
      context: ./layers/nginx
      dockerfile: Dockerfile
      args:
        - WEB_ROOT_PATH=${WEB_ROOT_PATH}
    container_name: ${COMPOSE_PROJECT_NAME}_web
    volumes:
      - ./app:${WEB_ROOT_PATH}
      - ./layers/nginx/templates:/etc/nginx/templates
    ports:
      - ${WEB_PORT}:10000
    depends_on:
      - php-fpm
    environment:
      - DOMAIN=${DOMAIN}
      - WEB_ROOT_PATH=${WEB_ROOT_PATH}
    networks:
      backend:
        aliases:
          - web
